//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnTime_Cover.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnTime_Cover.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no defects in this development..
        /// </summary>
        internal static string Dev_EmailDefectMessage {
            get {
                return ResourceManager.GetString("Dev_EmailDefectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no features in this development..
        /// </summary>
        internal static string Dev_EmailFeatureMessage {
            get {
                return ResourceManager.GetString("Dev_EmailFeatureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development Complete On .
        /// </summary>
        internal static string Dev_EmailSubject {
            get {
                return ResourceManager.GetString("Dev_EmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error gathering information from your OnTime Server..
        /// </summary>
        internal static string OnTime_Gathering_Error {
            get {
                return ResourceManager.GetString("OnTime_Gathering_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error sending your message!.
        /// </summary>
        internal static string Send_Email_Error {
            get {
                return ResourceManager.GetString("Send_Email_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your message has been sent successfully!.
        /// </summary>
        internal static string Send_Email_Success {
            get {
                return ResourceManager.GetString("Send_Email_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no defects in this cycle of testing..
        /// </summary>
        internal static string Test_EmailDefectMessage {
            get {
                return ResourceManager.GetString("Test_EmailDefectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no features in this cycle of testing..
        /// </summary>
        internal static string Test_EmailFeatureMessage {
            get {
                return ResourceManager.GetString("Test_EmailFeatureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing Complete On.
        /// </summary>
        internal static string Test_EmailSubject {
            get {
                return ResourceManager.GetString("Test_EmailSubject", resourceCulture);
            }
        }
    }
}
